### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by kzaidd**

### CODE REVIEW

**Comment by kanishk115** [comment]
hacktoberfest ke liye kar rha hai lya

**Comment by kzaidd** [comment]
Haa bhai, lekin kuch galat readme file nhi banaya hu

**Comment by kanishk115** [comment]
Ha voh maine padh liya tha readme.md file

**Comment by kanishk115** [comment]
Jo tune banaya

**Comment by kzaidd** [comment]
Thanks bhai

**Comment by kzaidd** [comment]
Tu nhi kr raha kya?

**Comment by kanishk115** [comment]
Kar rha hun na

**Comment by kzaidd** [comment]
Tujhe 3 baar aue pull request send karu? Accept karlega?

**Comment by kanishk115** [comment]
Maine files fork karke apne app ko fork request send kar rha hun and merge bhi khud kar diya

**Comment by kzaidd** [comment]
Haa toh maine tera readme update krdeta hu sirf bass accept krle

**Comment by kanishk115** [comment]
Karlunga

**Comment by kzaidd** [comment]
2 hogaye hai mere 2 baaki hai

**Pull request merged**
